
SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

SET NAMES utf8mb4;

DELIMITER //

CREATE TRIGGER quotes_before_insert
BEFORE INSERT ON quotes
FOR EACH ROW
BEGIN
    SET NEW.hash = MD5(NEW.text);
END;
//

CREATE TRIGGER quotes_before_update
BEFORE UPDATE ON quotes
FOR EACH ROW
BEGIN
    SET NEW.hash = MD5(NEW.text);
END;
//

DELIMITER ;

INSERT INTO quotes (text, author) VALUES ('Hledali jsme štěstí a našli jsme sebe.', 'John Lennon');
INSERT INTO quotes (text, author) VALUES ('Jediná cesta, které budete litovat, je ta, kterou nepodniknete.', NULL);
INSERT INTO quotes (text, author) VALUES ('Dítě není malý dospělý - učme ho žít, ne jen vědět.', 'Jean-Jacques Rousseau');
INSERT INTO quotes (text, author) VALUES ('Cesty nahoru a dolů jsou to samé.', 'Herákleitos');
INSERT INTO quotes (text, author) VALUES ('Když malířský štětec dělá to, co dělá, narazí na to, co by člověk nedokázal.', 'Robert Motherwell');
INSERT INTO quotes (text, author) VALUES ('Nikdy se nebojte říct: Tomu nerozumím!', 'Steve Rivkin');
INSERT INTO quotes (text, author) VALUES ('Civilizace zrodila potřeby, které člověk přirozeně nemá.', 'Jean-Jacques Rousseau');
INSERT INTO quotes (text, author) VALUES ('Člověk se rodí svobodný, ale všude je v okovech.', 'Jean-Jacques Rousseau');
INSERT INTO quotes (text, author) VALUES ('Problémy jsou tím, co činí život zajímavým a jejich překonávání je tím, co činí život smysluplným.', 'Joshua J. Marine');
INSERT INTO quotes (text, author) VALUES ('Není třeba dítě příliš vychovávat. Je třeba hezky žít. Dítě se přidá.', 'Ivan Štúr');
INSERT INTO quotes (text, author) VALUES ('Jestli najdeš v životě cestu bez překážek, určitě nikam nevede.', 'Arthur C. Clarke');
INSERT INTO quotes (text, author) VALUES ('Jediný skutečný konec je tento: John a Mary umřou. John a Mary umřou. John a Mary umřou. Tolik ke koncům. Začátky jsou vždycky mnohem zábavnější. Skuteční znalci si ovšem nejvíce vychutnávají ty stránky mezi nimi, protože ty se píšou nejhůř.', 'Margaret Atwoodová');
INSERT INTO quotes (text, author) VALUES ('Milovat někoho znamená pochopit i to, že vás nemiluje.', 'Romain Rolland');
INSERT INTO quotes (text, author) VALUES ('Nikdy si nikdo neplánoval, že bude na mizině, tlustý, líný, nebo hloupý. To se právě stává, když nemáte žádný plán.', 'Larry Winget');
INSERT INTO quotes (text, author) VALUES ('Neříkejte, že stará dáma křičela — popostrčte ji a nechte ji křičet.', 'Mark Twain');
INSERT INTO quotes (text, author) VALUES ('Důležitá věc je nepřestávat se ptát.', 'Albert Einstein');
INSERT INTO quotes (text, author) VALUES ('Ze všech lásek nejupřímnější je láska k jídlu.', 'George Bernard Shaw');
INSERT INTO quotes (text, author) VALUES ('Seděl jsem na podlaze japonského domu a díval jsem se ven na malou rozkvetlou zahrádku a poletující vážky. Najednou mě napadlo, že jsem se příliš dlouho vznášel nad zemí.', 'Mark Tobey');
INSERT INTO quotes (text, author) VALUES ('Společnost, která si ze všeho nejvíc váží pořádku, nebude tvůrčí. Bez správné míry nepořádku se tvořivost začne ztrácet jako v nějaké černé díře.', 'Lester Thurow');
INSERT INTO quotes (text, author) VALUES ('Spisovatel není definován vysokoškolským titulem.', 'Polly Adler');
INSERT INTO quotes (text, author) VALUES ('Bohatě zdobená próza je těžko stravitelná, obecně nezdravá a občas způsobuje nevolnost.', 'William Zinsser');
INSERT INTO quotes (text, author) VALUES ('Život je neobratně sestavená hostina, při níž se netrpělivě čeká na předkrm, zatímco kolem přešla v tichu hlavní pečeně.', 'Franz Kafka');
INSERT INTO quotes (text, author) VALUES ('Kdyby cestování bylo zadarmo, už nikdy byste mě neviděli.', NULL);
INSERT INTO quotes (text, author) VALUES ('Největším objevem mé generace je skutečnost, že lidská bytost může svůj život pozměnit tím, že k němu změní přístup.', 'William James');
INSERT INTO quotes (text, author) VALUES ('Jediné světlo mého života je světlo v ledničce.', NULL);
INSERT INTO quotes (text, author) VALUES ('Stromy rostou na Zemi pro blaho člověčenstva.', 'Bulharské lidové přísloví');
INSERT INTO quotes (text, author) VALUES ('Proč lidé nežijí ani z poloviny tak, jak vědí, že se má?', 'T. A. Harris');
INSERT INTO quotes (text, author) VALUES ('Kdo jinému jámu kopá je někde na brigádě.', NULL);
INSERT INTO quotes (text, author) VALUES ('K citovosti a citlivosti vychováváme nejvíce dítě tehdy, když se sami chováme citově a citlivě, bezprostředně a upřímně.', NULL);
INSERT INTO quotes (text, author) VALUES ('Životní pravidlo číslo jedna: Dělejte to, co Vám dělá radost.', NULL);
INSERT INTO quotes (text, author) VALUES ('Hlavní příčinou rozvodů je manželství.', 'Albert Einstein');
INSERT INTO quotes (text, author) VALUES ('Děti neznají minulost ani budoucnost, ale - což nám dospělým se stává zřídka - užívají si přítomnosti.', 'Jean de La Bruyére');
INSERT INTO quotes (text, author) VALUES ('Úspěšný muž je ten, který dokáže vydělat více peněz, než kolik dovede utratit jeho manželka. Úspěšná žena je ta, která takového muže najde.', 'Lana Turner');
INSERT INTO quotes (text, author) VALUES ('Kdo nikdy nebyl dítětem, nemůže se stát dospělým.', 'Ch. Chaplin');
INSERT INTO quotes (text, author) VALUES ('Dobří spisovatelé píší tak, že si je můžete přečíst nahlas a pochopíte smysl. Špatní spisovatelé musejí být zkoumáni a znovu čteni.', 'Scot McKnight');
INSERT INTO quotes (text, author) VALUES ('To nejdůležitější, co můžeš svým dětem dát, mnohem důležitější než cokoli materiálního, je pocit sebedůvěry.', NULL);
INSERT INTO quotes (text, author) VALUES ('Nekráčej přede mnou, možná za tebou nepůjdu.\nNekráčej za mnou, možná tě nedokážu vést.\nKráčej vedle mě a buď můj přítel.\n', 'Albert Camus');
INSERT INTO quotes (text, author) VALUES ('Nebojte se vzdát dobrého kvůli skvělému.', 'John D. Rockefeller');
INSERT INTO quotes (text, author) VALUES ('Člověk musí jet daleko, hrozně daleko, aby se dostal co nejblíž k domovu.', 'Karel Čapek');
INSERT INTO quotes (text, author) VALUES ('Vypravování je nejlepší způsob, jak vypustit myšlenky do současného světa.', 'Robert McKee');
INSERT INTO quotes (text, author) VALUES ('Nic se neopakuje, fantazie přírody je neopakovatelná.', NULL);
INSERT INTO quotes (text, author) VALUES ('Podstatou lásky nejsou drahé dary, ale drazí lidé.', 'George Sandová');
INSERT INTO quotes (text, author) VALUES ('Jako že kreslení by mělo být bez zbytečných čar a stroje bez zbytečných částí?', 'Strunk and White');
INSERT INTO quotes (text, author) VALUES ('Tři slova, která chce žena slyšet ze všeho nejvíc: Já to umyju.', 'Molly Shannonová');
INSERT INTO quotes (text, author) VALUES ('Idioti jsou jako láska: dá se o nich mluvit donekonečna.', 'Gustav Flaubert');
INSERT INTO quotes (text, author) VALUES ('Neexistují tajemství úspěchu, je to výsledek přípravy, tvrdé práce a učení se z neúspěchu.', 'Colin Powell');
INSERT INTO quotes (text, author) VALUES ('Život má dvě pravidla. Pravidlo číslo jedna - nikdy nepřestat. Pravidlo číslo dvě - vždy pamatovat na pravidlo číslo jedna.', NULL);
INSERT INTO quotes (text, author) VALUES ('Přestaňte se honit za penězi a začněte se honit za vášní.', 'Tony Hsieh');
INSERT INTO quotes (text, author) VALUES ('Za 20 let vám budou mnohem víc vadit věci, které jste neudělali. Mnohem víc, než ty, které jste udělali. Takže zahoďte svoji zaprděnost. Odplujte od bezpečného břehu. Chyťte dobrodružný vítr. Objevujte. Sněte. Zkoumejte.', 'Mark Twain');
INSERT INTO quotes (text, author) VALUES ('Bisexualita zdvojnásobuje naše vyhlídky na schůzku v sobotu večer.', 'Woody Allen');
INSERT INTO quotes (text, author) VALUES ('Člověk, který cestuje s touhou dozvědět se, cestuje přes všechny dálky, hlavně k sobě samému.', 'Jan Werich');
INSERT INTO quotes (text, author) VALUES ('Jestliže myslí všichni stejně, potom někdo nemyslí.', 'George Patton');
INSERT INTO quotes (text, author) VALUES ('Velký je ten člověk, který neztratil své dětské srdce.', 'J. A. Komenský');
INSERT INTO quotes (text, author) VALUES ('Být šťastný neznamená, že je všechno perfektní. Znamená to, že jste se rozhodli podívat se za hranice nedokonalosti.', NULL);
INSERT INTO quotes (text, author) VALUES ('Na inspiraci nemůžete čekat. Musíte jí pronásledovat s palicí.', 'Jack London');
INSERT INTO quotes (text, author) VALUES ('Nebyl jsem ještě všude, ale mám to na svém seznamu.', NULL);
INSERT INTO quotes (text, author) VALUES ('Lži jsou pravdy ostatních lidí.', 'Oscar Wilde');
INSERT INTO quotes (text, author) VALUES ('Nevím, jak mohou můj život ovlivňovat hvězdy vzdálené miliony kilometrů víc, než stromy a lidé v mé blízkosti.', NULL);
INSERT INTO quotes (text, author) VALUES ('Jděte tam, kde si Vás cení, ne tam, kde Vás tolerují. Pokud nevidí Vaši skutečnou hodnotu, pak je čas na změnu a nový začátek.', NULL);
INSERT INTO quotes (text, author) VALUES ('Kdo chce hýbat světem, musí pohnout nejdříve sám sebou.', 'Sókratés');
INSERT INTO quotes (text, author) VALUES ('Rozdíl mezi mnou a Sylvesterem Stallonem je v tom, že já jsem já a on je on.', 'Arnold Schwarzenegger');
INSERT INTO quotes (text, author) VALUES ('Soustřeďte se na to, kam chcete jít, nikoli na to, čeho se bojíte.', 'Anthony Robbins');
INSERT INTO quotes (text, author) VALUES ('Myslím si dokonce, že nedokáže milovat; je příliš zaujat jinými myšlenkami a nápady, než aby se mohl pevně připoutat k nějakému člověku.', 'Anna Dostojevská');
INSERT INTO quotes (text, author) VALUES ('Úsměv, který vyšleš, se k tobě vrátí.', 'indické přísloví');
INSERT INTO quotes (text, author) VALUES ('Jediná věc, která stojí mezi Vámi a Vaším snem, je vůle zkusit to a víra, že je to možné.', 'Joel Brown');
INSERT INTO quotes (text, author) VALUES ('Způsob, jak začít, je přestat mluvit a začít dělat.', 'Walt Disney');
INSERT INTO quotes (text, author) VALUES ('Vraťme se k přírodě!', 'Jean-Jacques Rousseau');
INSERT INTO quotes (text, author) VALUES ('Zapomeňte na všechny důvody, proč by to nemělo fungovat, a najděte jeden, proč to fungovat bude.', NULL);
INSERT INTO quotes (text, author) VALUES ('Aby se umělecké dílo stalo skutečně nesmrtelným, musí se vymknout všem lidským hranicím: logika a zdravý rozum budou jen překážet. Až se však jednou tyto překážky prolomí, dílo vstoupí do království dětských vizí a snů.', 'Giorgio De Chirico');
INSERT INTO quotes (text, author) VALUES ('Lesy člověka uživí, jestli s nimi bude žít a ne je ničit.', 'F. Carte');
INSERT INTO quotes (text, author) VALUES ('Když jdou kořeny hluboko, netřeba se bát větru.', 'Čínské přísloví');
INSERT INTO quotes (text, author) VALUES ('Představivost vládne světu.', 'Napoleon Bonaparte');
INSERT INTO quotes (text, author) VALUES ('Každý obraz se vyvíjí svým vlastním způsobem… Když je obraz hotový, jeho téma se odhalí.', 'William Baziotes');
INSERT INTO quotes (text, author) VALUES ('Příběhy nám říkají, co jsme věděli, ale zapomněli; a připomínají nám, co jsme si ještě nepředstavili.', 'Anne Watson');
INSERT INTO quotes (text, author) VALUES ('Uprostřed každého problému se nachází příležitost.', 'Albert Einstein');
INSERT INTO quotes (text, author) VALUES ('Největší zlo je chtít vládnout nad druhými, aniž bychom ovládli sami sebe.', 'Jean-Jacques Rousseau');
INSERT INTO quotes (text, author) VALUES ('Představivost je důležitější než vědomosti.', 'Albert Einstein');
INSERT INTO quotes (text, author) VALUES ('Cestuj často. Čím víckrát se ztratíš, tím víc nalezneš sám sebe.', NULL);
INSERT INTO quotes (text, author) VALUES ('Chystáte-li se napsat moralitu, uděláte nejlíp, když nebudete ani vědět, co to morálka je.', 'Lindsay, americký teoretik dramatu');
INSERT INTO quotes (text, author) VALUES ('Nikdo si nesmí nikdy myslet, že je něco víc, něco lepšího, než ten druhý. Možná, že toho má víc v makovici, možná, že nosí lepší košili, možná, že má fortelnější ruce, možná, že má větší bicepsy. Ale tohle všechno ho jenom zavazuje, aby toho udělal tím více pro ty s menšími bicepsy a s horší košilí. [Jan Werich]', NULL);
INSERT INTO quotes (text, author) VALUES ('Milovat je poznat sám sebe v někom jiném.', 'Eckhart Tolle');
INSERT INTO quotes (text, author) VALUES ('Dnes je první den zbytku tvého života.', 'Anne Wilson Schaef');
INSERT INTO quotes (text, author) VALUES ('Nebojte se chyb. Žádné neexistují.', 'Miles Davis');
INSERT INTO quotes (text, author) VALUES ('Banka je místo, kde vám půjčí peníze, pokud se vám podaří dokázat, že je nepotřebujete.', 'Bob Hope');
INSERT INTO quotes (text, author) VALUES ('Když píšu knihu nebo povídku, začnu psát každé ráno co nejdříve po rozednění. Nikdo mě neruší, je chladno a psaní mě zahřeje.', 'Ernest Hemingway');
INSERT INTO quotes (text, author) VALUES ('Předstírám že pracuji, protože firma předstírá že mě platí.', NULL);
INSERT INTO quotes (text, author) VALUES ('Když mají manželé problémy tak za to můžou vždy obě strany. Jak manželka tak i tchýně.', NULL);
INSERT INTO quotes (text, author) VALUES ('Stromy jsou básně, které země píše do nebe.', 'Ch. Fibrin');
INSERT INTO quotes (text, author) VALUES ('To, co je už za námi a to co je před námi jsou maličkosti ve srovnání s tím, co je uvnitř nás.', 'Ralph Emerson');
INSERT INTO quotes (text, author) VALUES ('Někde ve světě je velice zklamaná pláž a přemítá, proč na ní právě teď neležím.', NULL);
INSERT INTO quotes (text, author) VALUES ('Přemýšlíme o tom, co vidíme a slyšíme. To, o čem přemýšlíme, v nás vyvolává pocity. Naše pocity ovlivňují naše reakce. Reakce se mění v návyky, které určují náš úděl.', 'Bob Gass');
INSERT INTO quotes (text, author) VALUES ('Příležitosti mají mnoho převleků.', 'Albert Mensah');
INSERT INTO quotes (text, author) VALUES ('Ne, děkuji, já si nevybojovala pozici na vrcholku potravního řetězce jen proto, abych se stala veganem.', NULL);
INSERT INTO quotes (text, author) VALUES ('Dokud pařez nevyhnije, není strom zapomenut.', NULL);
INSERT INTO quotes (text, author) VALUES ('Ne místo, ne podmínky, ale mysl je tím, co může učinit každého šťastným nebo nešťastným.', 'Roger Lestrange');
INSERT INTO quotes (text, author) VALUES ('Člověka, který se nikdy nevzdává, zkrátka nikdy neporazíte.', 'Babe Ruth');
INSERT INTO quotes (text, author) VALUES ('Pokud získáte pojem o čase, začněte s ním počítat.', 'Zig Ziglar');
INSERT INTO quotes (text, author) VALUES ('Klenot nebe je slunce, klenot domu je dítě.', 'čínské přísloví');
INSERT INTO quotes (text, author) VALUES ('Pro obyčejného člověka, jehož mysl se podobá protichůdných úvah, názorů a předsudků, je prakticky nemožné vynaložit prostou pozornost.', NULL);
INSERT INTO quotes (text, author) VALUES ('Proč vlastně musí být "Bůh" podstatné jméno? Proč ne sloveso… ten nejaktivnější a nejdynamičtější ze všech?', 'Mary Dalyová');
INSERT INTO quotes (text, author) VALUES ('Bolest, kterou cítíte dnes, je síla, kterou pocítíte zítra. Každá výzva, s kterou se setkáte, je příležitost k růstu.', NULL);
INSERT INTO quotes (text, author) VALUES ('Štěstí není něco, co k člověku přijde jen tak. Přichází spolu s našimi činy.', 'Dalajláma');
INSERT INTO quotes (text, author) VALUES ('Veškerý pokrok se děje mimo zónu komfortu.', 'Michael John Bobak');
INSERT INTO quotes (text, author) VALUES ('Kdo chce lesu porozumět, měl by se ho nejdříve naučit poslouchat.', NULL);
INSERT INTO quotes (text, author) VALUES ('K tomu, abychom jasně viděli, často stačí jen změnit úhel pohledu.', 'Antoine de Saint Exupéry');
INSERT INTO quotes (text, author) VALUES ('Autor má vždycky dva úkoly: odhalit charakter a změnit charakter.', 'Ed McKee');
INSERT INTO quotes (text, author) VALUES ('Největší neúspěch, který můžete v životě mít, je, že uděláte tu chybu, že se nebudete snažit.', NULL);
INSERT INTO quotes (text, author) VALUES ('Tvůj čas je omezen. Proto ho neztrácej tím, že budeš žít život někoho jiného.', 'Steve Jobs');
INSERT INTO quotes (text, author) VALUES ('Jeden z největších klíčů k úspěchu je mít disciplínu dělat to, co víte, že byste měli dělat, i když se Vám zrovna nechce.', NULL);
INSERT INTO quotes (text, author) VALUES ('Pokud chcete žít naplno, musíte mít smysl pro perspektivu. Život je nesrovnatelně významnější než Vaše maličkost, jíž jste dali sílu vás rozčilovat.', 'Anthony de Mello');
INSERT INTO quotes (text, author) VALUES ('Cestování a změna místa dodávají mysli novou sílu.', 'Seneca');
INSERT INTO quotes (text, author) VALUES ('Neseme si s sebou počasí svého života', 'Stephen Covey');
INSERT INTO quotes (text, author) VALUES ('V dnešním rychle měnícím se světě jsou ti lidé, kteří neriskují, nejvíce vystaveni riziku.', 'Robert Kiyosaki');
INSERT INTO quotes (text, author) VALUES ('Nejvzácnější klenoty, které můžete mít kolem krku, jsou vaše děti.', NULL);
INSERT INTO quotes (text, author) VALUES ('I když se nikdo nemůže vrátit a vytvořit zcela nový začátek, každý může začít teď a vytvořit zcela nový konec.', 'Carl Bard');
INSERT INTO quotes (text, author) VALUES ('Pravý účel není v podstatě nic jiného, než aby naše škola byla dílnou lidskosti a předehrou života. Aby zde probíhalo vše, co člověka činí člověkem.', 'Komenský, Škola hrou');
INSERT INTO quotes (text, author) VALUES ('Dělejte to, z čeho máte strach. A dělejte to opakovaně. To je nejrychlejší a nejjistějších způsob, jak strach porazit.', 'Dale Carnegie');
INSERT INTO quotes (text, author) VALUES ('Protože lidé nedovedou ocenit přítomnost a naplnit ji životem, touží tolik po lepší budoucnosti a koketují tolik s minulostí.', 'J. W. Goethe');
INSERT INTO quotes (text, author) VALUES ('Přijměte odpovědnost za Váš život. Vězte, že jste to Vy, kdo Vás dostane tam, kam chcete, nikdo jiný to neudělá.', 'Les Brown');
INSERT INTO quotes (text, author) VALUES ('Domov je tam, kde je srdce. A mé srdce je vždy tam, kde právě jsem.', 'Lily Leung');
INSERT INTO quotes (text, author) VALUES ('Fantazie je mnohem důležitější než znalosti, protože fantazie je bez hranic. Tvořivost je v mém životě důležitá. Ostatně dílo vědce klíčí na půdě imaginace.', 'Albert Einstein');
INSERT INTO quotes (text, author) VALUES ('I suchý strom oživuje krajinu.', 'Japonské přísloví');
INSERT INTO quotes (text, author) VALUES ('Zákony nejsou spravedlivé tím, že existují, ale tehdy, když vycházejí z vůle lidu.', 'Jean-Jacques Rousseau');
INSERT INTO quotes (text, author) VALUES ('Příběh je odkládaná odpověď.', 'Daniela Fischerová');
INSERT INTO quotes (text, author) VALUES ('Řekni mnoho, napiš málo.', 'Ellen Lupton');
INSERT INTO quotes (text, author) VALUES ('Čím jste je to, čím jste byli, a čím budete je to, co děláte teď.', 'Buddha');
INSERT INTO quotes (text, author) VALUES ('Děti nemají čas na blbosti, jsou šťastné teď.', NULL);
INSERT INTO quotes (text, author) VALUES ('Nejlepší cesta jak mít dobrý nápad, je mít hodně nápadů.', 'Linus Pauling');
INSERT INTO quotes (text, author) VALUES ('Nemohu vám dát vzorec pro úspěch, ale mohu vám dát vzorec pro neúspěch - a ten je: Snažte se potěšit všechny okolo.', 'Herbert Bayard Swope');
INSERT INTO quotes (text, author) VALUES ('Nikdy neváhejte vyrazit daleko, za všechna moře, za všechny hranice, země či víry.', 'Amin Maalouf');
INSERT INTO quotes (text, author) VALUES ('Lepší pivo v žaludku nežli voda na plicích.', 'Jára Cimrman');
INSERT INTO quotes (text, author) VALUES ('Je těžké selhat, ale je horší nikdy se nepokusit o úspěch.', 'Theodore Roosevelt');
INSERT INTO quotes (text, author) VALUES ('O kamenech bylo známo, že se hýbají, o stromech, že mluví.', 'W. Shakespeare');
INSERT INTO quotes (text, author) VALUES ('Moje peněženka je hodně podobná cibuli. Jakmile se podívám dovnitř, chce se mi brečet.', NULL);
INSERT INTO quotes (text, author) VALUES ('Akce je základním klíčem k úspěchu.', 'Pablo Picasso');
INSERT INTO quotes (text, author) VALUES ('Talent je schopnost rozeznat tři věci tam, kde si ostatní lidé všimnou jenom jedné.', 'Arnošt Lustig');
INSERT INTO quotes (text, author) VALUES ('Existuje tisíce způsobů, jak zabít čas, ale žádný, jak ho vzkřísit.', 'Albert Einstein');
INSERT INTO quotes (text, author) VALUES ('Nerozumějí okamžikům.', 'Milan Zelený');
INSERT INTO quotes (text, author) VALUES ('Jestliže, jste během dne neobjevili nic zvláštního, pak jste z toho dne moc neměli.', 'John Wheeler');
INSERT INTO quotes (text, author) VALUES ('Cestování není nikdy otázkou peněz, nýbrž odvahy.', 'Paulo Coelho');
INSERT INTO quotes (text, author) VALUES ('Hoře nedodává ušlechtilého vzhledu výška, nýbrž stromoví.', 'Japonské rčení');
INSERT INTO quotes (text, author) VALUES ('Vědomosti jsou síla, ale teprve nadšení zapne spínač.', 'Ivern Ball');
INSERT INTO quotes (text, author) VALUES ('Objevovat vlastní schopnosti je úžasně zábavné.', 'Kjell A Nördström');
INSERT INTO quotes (text, author) VALUES ('Slova, která říkám nebo píši, utvářejí cestu po níž kráčím.', 'Diane Glancy');
INSERT INTO quotes (text, author) VALUES ('Představivost je zdrojem pokroku. V blízké budoucnosti bude dokonce pro národy znamenat tvůrčí fantazie více než přírodní bohatství. Jedna země předstihne druhou v té míře, v jaké bude mít více imaginativních mozků.', 'Joseph Basile, francouzský sociolog');
INSERT INTO quotes (text, author) VALUES ('Naše hlava je kulatá, aby myšlení mohlo měnit směr. Kreativita znamená vidět to, co vidí ostatní, ale něco jiného si u toho myslet.', 'Francis Picabia');
INSERT INTO quotes (text, author) VALUES ('Do hloubky může dosáhnout strom svými kořeny, do dálky svými semeny.', NULL);
INSERT INTO quotes (text, author) VALUES ('Veškerá umění, kterým se věnujeme, jsou pouhým učňovstvím. Oním skutečně velkým uměním je náš život.', 'M. C. Richards');
INSERT INTO quotes (text, author) VALUES ('Úspěch není konečný, neúspěch není fatální: odvaha pokračovat je to, co se počítá.', 'Winston S. Churchill');
INSERT INTO quotes (text, author) VALUES ('Každý má talent. Je to jenom otázka hledání, dokud nezjistíte, co to je.', 'George Lucas');
INSERT INTO quotes (text, author) VALUES ('Umělci, kteří hledají dokonalost ve všem, jsou ti, kdo ji nemohou dosáhnout v ničem.', 'Eugéne Delacroix');
INSERT INTO quotes (text, author) VALUES ('Začínal jsem z ničeho a většinu z toho pořád mám.', NULL);
INSERT INTO quotes (text, author) VALUES ('Člověk je od přírody dobrý - společnost ho kazí.', 'Jean-Jacques Rousseau');
INSERT INTO quotes (text, author) VALUES ('Ne každý, kdo bloudí, je ztracen.', 'J. R. R. Tolkien');
INSERT INTO quotes (text, author) VALUES ('Inovace spočívá v otázce: Co kdyby?', 'Jonas Ridderstrale');
INSERT INTO quotes (text, author) VALUES ('Ty nejlepší vztahy obvykle začínají nečekaně.', 'Ralph Smart');
INSERT INTO quotes (text, author) VALUES ('Stres vyvolávají síly působící protichůdným směrem. Nedejte se a zachovejte klid.', NULL);
INSERT INTO quotes (text, author) VALUES ('Mysl je jako padák. Funguje jenom, když je otevřená.', 'Zig Ziglar');
INSERT INTO quotes (text, author) VALUES ('Život není náhoda, ale volba. Nejdůležitější není, co se děje, ale jak si s tím poradíme. Naše volba - co si myslet a co dělat je to nejdůležitější.', 'Hal Urban');
INSERT INTO quotes (text, author) VALUES ('Neexistuje příběh bez autora.', 'Jiří Trávníček');
INSERT INTO quotes (text, author) VALUES ('Úspěch se zdá být spojen s akcí. Úspěšní lidé se stále pohybují, dělají chyby, ale nekončí.', 'Conrad Hilton');
INSERT INTO quotes (text, author) VALUES ('Příklad není to nejdůležitější, čím působíme na druhé lidi. Příklad je to jediné, čím je ovlivňujeme.', 'Albert Schweitzer');
INSERT INTO quotes (text, author) VALUES ('Pro společnost jsou přínosem jak optimisté, tak pesimisté. Ti první totiž dokážou vymyslet letadlo, zatímco ti druzí k němu vymyslí padák.', 'Gil Stern');
INSERT INTO quotes (text, author) VALUES ('Srovnejme výrok Zemřel král a zemřela královna s větou Král zemřel, načež žalem zemřela i královna. Tento příklad, s nímž přišel romanopisec E. M. Forster, poukazuje na zřejmý rozdíl mezi pouhou posloupností faktů a tím, co už utváří děj, příběh.', 'Nassim Nicholas Taleb [Černá labuť]');
INSERT INTO quotes (text, author) VALUES ('Strom neodepře svůj stín ani tomu, kdo ho přichází porazit.', 'Malajské přísloví');
INSERT INTO quotes (text, author) VALUES ('Od člověka se žádá, aby ze sebe učinil to, co se z něj má stát, aby naplnil svůj osud.', 'Paul Tillich');
INSERT INTO quotes (text, author) VALUES ('Jedna z nejlepších věcí na cestování je zjištění, jak mnoho dobrých a milých lidí tam venku je.', 'Edith Wharton');
INSERT INTO quotes (text, author) VALUES ('Spíš než napomínání potřebují děti své vzory.', 'Joseph Joubert');
INSERT INTO quotes (text, author) VALUES ('Za rok si budete přát, abyste začali dnes.', 'Karen Lamb');
INSERT INTO quotes (text, author) VALUES ('Kdo nemiluje stromy, ať netvrdí, že miluje člověka.', 'John Ruskin');
INSERT INTO quotes (text, author) VALUES ('Nad alkoholem nelze zvítězit, jen Moraváci remizovali.', NULL);
INSERT INTO quotes (text, author) VALUES ('Nelituji ničeho, co jsem udělala. Lituji pouze toho, co jsem neudělala, když jsem měla šanci.', 'tajná neznámá');
INSERT INTO quotes (text, author) VALUES ('Varování: Přežírání může zmenšovat oblečení.', NULL);
INSERT INTO quotes (text, author) VALUES ('Jít do neznáma je lepší než zůstat tam, kde nic není.', 'Spencer Johnson');
INSERT INTO quotes (text, author) VALUES ('Všimli jste si toho někdy? Každý, kdo jde pomaleji než vy, je idiot, zatímco všichni, kteří kráčejí rychleji, jsou maniaci.', 'George Carlin');
INSERT INTO quotes (text, author) VALUES ('Práce ti neuteče, když ukážeš svému dítěti duhu, ale duha nepočká, až budeš hotová s prací.', NULL);
INSERT INTO quotes (text, author) VALUES ('Zplácanost není pouze narušitelem prózy, je to také ničitelka života a naděje:\r\nSmrt na dálnici způsobená špatně umístěnou značkou;\r\nzlomená srdce milenců díky nesprávné frázi v dobře míněném dopise;\r\nbolestné čekání turisty na někoho, kdo nepřijede kvůli nedbalému telegramu.\r\nMyslete na tragédie, které spočívají v nejednoznačnosti!\r\nKdyž chcete něco říct, ujistěte se, že jste to řekli.\r\n', 'Strunk and White');
INSERT INTO quotes (text, author) VALUES ('Člověk bez smíchu je jako strom bez květu.', 'Osho');
INSERT INTO quotes (text, author) VALUES ('Ze všeho nejvíc dělejte věci, které milujete. Pokud tomu tak není, nedělejte je.', 'Coffee Heaven');
INSERT INTO quotes (text, author) VALUES ('Když budete stále dělat, co jste vždycky dělali, dostanete pouze to, co jste vždycky dostávali.', 'Susan Jeffers');
INSERT INTO quotes (text, author) VALUES ('Neschovávejte si věci, které se zdají být dobré, na pozdější dobu nebo pro jinou knihu. \r\nUplatněte je, uplatněte je všechny, uplatněte je teď.\r\nImpuls, že si chcete něco ponechat do budoucna, znamená udělej to hned.\r\nPozději se objeví něco nového, něco ještě lepšího.\r\n', 'Annie Dillard');
INSERT INTO quotes (text, author) VALUES ('Člověk beze snů je strom bez kořenů.', 'Otakar Matušek');
INSERT INTO quotes (text, author) VALUES ('Padni sedmkrát, postav se osmkrát.', 'japonské přísloví');
INSERT INTO quotes (text, author) VALUES ('I v tom nejhustším lese najdete osamělý strom.', NULL);
INSERT INTO quotes (text, author) VALUES ('Odmítne-li žena tvoji lásku a nabídne ti přátelství, nepovažuj to za rozchod. Znamená to, že chce postupovat podle pořadí.', 'Molière');
INSERT INTO quotes (text, author) VALUES ('Jsem z Prahy a jsem abstinent. Tak nevím, co je horší.', NULL);
INSERT INTO quotes (text, author) VALUES ('Život není o hledání sebe sama, ale o vytváření sebe sama.', 'George Bernard Shaw');
INSERT INTO quotes (text, author) VALUES ('Když někdo chce zkazit životní dráhu svých dětí, ať jim odstraní z cesty všechny překážky.', 'Oesch');
INSERT INTO quotes (text, author) VALUES ('Proč lidé, kteří nemají čas, obvykle udělají tak málo práce?', NULL);
INSERT INTO quotes (text, author) VALUES ('Abyste uspěli, musí být Vaše touha po úspěchu větší než strach z neúspěchu.', 'Bill Cosby');
INSERT INTO quotes (text, author) VALUES ('S husím brkem v ruce a několika listy papíru před sebou se vysměji celému vesmíru!', 'P. Aretino');
INSERT INTO quotes (text, author) VALUES ('Pokud nejste ochotni mimořádně riskovat, musíte se spokojit s obyčejností.', 'Jim Rohn');
INSERT INTO quotes (text, author) VALUES ('Chceš-li hodnou ženu, buď správným mužem.', 'Johann Wolfgang Goethe');
INSERT INTO quotes (text, author) VALUES ('Neříkejte, že nemáte dost času. Máte k dispozici úplně stejně hodin denně, kolik měl Michelangelo, Kryštof Kolumbus, T.A.Edison, Albert Einstein nebo Winston Churchill.', 'Brown H. Jackson');
INSERT INTO quotes (text, author) VALUES ('Stromy a ženy tají svá léta. Stromy však vydrží mlčet déle.', 'Ivan Fontana');
INSERT INTO quotes (text, author) VALUES ('Cíl můžete snadno minout, když míříte moc vysoko. Stejně tak ho však můžete minout, když míříte moc nízko.', 'Thomas Fuller');
INSERT INTO quotes (text, author) VALUES ('Jděte do toho! Zkoumejte všechny věci intenzivně a vytrvale. Hledejte v každém objektu umělecké dílo. Nenechávejte ho běžným, jako kdybyste ho pochopili, ale místo toho jděte pod povrch, až ho uvidíte v jeho plné síle, zvláštnosti a jedinečnosti.', 'Dillard');
INSERT INTO quotes (text, author) VALUES ('Nedostatek času neexistuje. Všichni máme dost času, abychom mohli udělat všechno, co opravdu udělat chceme.', 'Alan Lakein');
INSERT INTO quotes (text, author) VALUES ('Štěstí si nelze přivlastnit, získat ho nebo ztratit. Štěstí je duchovní prožitek žít každou minutu v lásce, milosti a vděčnosti.', 'Denis Waitley');
INSERT INTO quotes (text, author) VALUES ('Nikdy nedovolte včerejšku, aby zneužíval dnešek.', 'Nelson Richard');
INSERT INTO quotes (text, author) VALUES ('Každý úspěšný kus literatury faktu by měl čtenáři nabídnout jednu provokativní myšlenku, kterou předtím nikdy neslyšel. Ne dvě myšlenky, ani pět - pouze jednu.', 'Joseph Epstein');
INSERT INTO quotes (text, author) VALUES ('Kreativita je… vidět něco, co dosud neexistuje.', 'Michele Sheaová');
INSERT INTO quotes (text, author) VALUES ('Muž neumí přežít tolik utrpení, kolik dokáže přežít žena.', 'Osho');
INSERT INTO quotes (text, author) VALUES ('Neříkej mi, jaké vzdělání máš. Řekni mi, jak velkou část světa jsi viděl.', NULL);
INSERT INTO quotes (text, author) VALUES ('Pokud řeknete Je to těžké, ve skutečnosti to znamená, že nemáte dost sil za to bojovat. Přestaňte to říkat. Myslete pozitivně.', NULL);
INSERT INTO quotes (text, author) VALUES ('Prastarý rybník. Skočila do něj žába. Žbluňk.', 'Bašó, japonský básník, 17. století');
INSERT INTO quotes (text, author) VALUES ('Jediný způsob, jak odvádět skvělou práci, je milovat to, co děláte. Pokud jste takovou ještě nenašli, nespokojte se s ní a jděte dál.', 'Steve Jobs');
INSERT INTO quotes (text, author) VALUES ('Loď je v bezpečí, když je v přístavu. Ale pro tento účel se lodě nestavějí.', 'John A. Shedd');
INSERT INTO quotes (text, author) VALUES ('Po čase toužíme ze všeho nejvíce, ale běda! Zacházíme s ním nejhůře.', 'William Penn');
INSERT INTO quotes (text, author) VALUES ('Láska je jako válka - je snadné ji začít, ale nesnadné ji ukončit.', 'H. L. Mencken');
INSERT INTO quotes (text, author) VALUES ('Dobré zvyky se těžce nabývají, ale snadno se s nimi žije. Zlozvyky se snadno získávají, ale život s nimi je obtížný.', 'Zig Ziglar');
INSERT INTO quotes (text, author) VALUES ('Příběhy jsou nejúčinnější zbraní ve výbavě vůdce.', 'Howard Gardner, Harvard University');
INSERT INTO quotes (text, author) VALUES ('Pocit úspěchu je podobný pocitu pádu. Až na jeden rozdíl - nic vás nemůže zastavit.', 'Maciej Ceglowski');
INSERT INTO quotes (text, author) VALUES ('Víte co je horší, než být slepý? Mít v pořádku zrak a nevidět.', 'Helen Keller');
INSERT INTO quotes (text, author) VALUES ('Vychovávat dítě znamená vychovávat sebe.', 'anglické přísloví');
INSERT INTO quotes (text, author) VALUES ('Dobrá žena muže inspiruje, vtipná ho zaujme, krásná ho okouzlí, ale soucitná ho dostane.', 'Victor Hugo');
INSERT INTO quotes (text, author) VALUES ('Chcete uspět? Zdvojnásobte počet svých neúspěchů!', 'Tom Watson');
INSERT INTO quotes (text, author) VALUES ('Výplata - Jeden z důkazů, že i zaměstnavatel má smysl pro humor.', NULL);
INSERT INTO quotes (text, author) VALUES ('Než půjdete zlepšovat svět, projděte se třikrát vlastním domem.', 'čínské přísloví');
INSERT INTO quotes (text, author) VALUES ('Víte, všechno je vypravování. A právě o tom je novinařina.', 'Tom Brokaw');
INSERT INTO quotes (text, author) VALUES ('Děti potřebují spíš vzory než kritiku.', 'Joseph Joubert');
INSERT INTO quotes (text, author) VALUES ('Když často kritizujete své děti, nepřestanou vás milovat. Přestanou milovat sebe.', 'Rudraksha');
INSERT INTO quotes (text, author) VALUES ('Budete-li pilně osm hodin denně pracovat, možná se vám nakonec podaří stát se šéfem a pracovat dvanáct hodin denně.', 'Robert Frost');
INSERT INTO quotes (text, author) VALUES ('Život je umění kreslit bez možnosti gumovat.', 'J. W. Gardner');
INSERT INTO quotes (text, author) VALUES ('V dětství je celý svět starší než my.', 'Greene');
INSERT INTO quotes (text, author) VALUES ('Příběh, všechno má příběh - jen ho stačí vidět.', 'Bohumil Hrabal');
INSERT INTO quotes (text, author) VALUES ('Nový život začíná tam, kde starý končí. A nové otázky si položíte, když pohřbíte staré odpovědi. Buďte při tom rozvážní, ale odhodlaní.', NULL);
INSERT INTO quotes (text, author) VALUES ('Příběh je základním principem myšlení.', 'Mark Turner');
INSERT INTO quotes (text, author) VALUES ('Svoboda je každá moje hodina. Jedna z největších je ta, že říkám, co si myslím. Ať to má jakýkoliv dopad. A jsem si vědom, že někdy říkám kraviny. Ale jsou moje.', 'Jan Kraus');
INSERT INTO quotes (text, author) VALUES ('Zapamatujte si toto: Dobře napsaná kniha se špatnými argumenty bude mít mnohem větší vliv, než špatně napsaná kniha s nekonečným množstvím nuancí. A zapamatujte si také: bezduchá próza vzniká z bezduchého myšlení.', 'Scot McKnight');
INSERT INTO quotes (text, author) VALUES ('Milovat znamená dávat, ne vlastnit.', 'Jean-Jacques Rousseau');
INSERT INTO quotes (text, author) VALUES ('Dospělí čekají celý týden na pátek, celý rok na léto a celý život na štěstí.', NULL);
INSERT INTO quotes (text, author) VALUES ('Hledej v člověku strom, hluboké kořeny, pevný kmen a košatou korunu.', 'Japonské přísloví');
INSERT INTO quotes (text, author) VALUES ('Držte se dál od všech, kteří Vás okrádají o radost. Život je příliš krátký na to, abyste ho trávili s hlupáky.', NULL);
INSERT INTO quotes (text, author) VALUES ('Láska žije v tom, kdo miluje, nikoli v tom, kdo je milován.', 'Romain Rolland');
INSERT INTO quotes (text, author) VALUES ('Stvořila jsem si svůj svět, a je to mnohem lepší svět, než jaký jsem kdy viděla venku.', 'Louise Nevelsonová');
INSERT INTO quotes (text, author) VALUES ('Strom, který nekvetl, nemůže mít plody.', 'Japonské přísloví');
INSERT INTO quotes (text, author) VALUES ('Nebojte se selhání. Strachujte se o tu šanci, která Vám uteče, když to nezkusíte.', 'Jack Canfield');
INSERT INTO quotes (text, author) VALUES ('Je těžké milovat ženu a současně dělat něco rozumného.', 'Lev Nikolajevič Tolstoj');
INSERT INTO quotes (text, author) VALUES ('Čím více víš, tím méně potřebuješ.', 'Yvon Chouinard');
INSERT INTO quotes (text, author) VALUES ('Neexistuje morální nebo nemorální kniha. Knihy jsou buď dobře, nebo špatně napsané. Toť vše.', 'Oscar Wilde');
INSERT INTO quotes (text, author) VALUES ('Každý potřebuje strom, od kolébky po rakev.', 'Mohamed');
INSERT INTO quotes (text, author) VALUES ('Nepokoušejte se stát úspěšnou osobou, ale raději se pokuste stát se hodnotnou osobou.', 'Albert Einstein');
INSERT INTO quotes (text, author) VALUES ('Vyprávění je myšlenkový modul, který lidstvo vyvinulo, aby mu pomohl chápat vztah mezi příčinou a následkem.', 'Chris Crawford');
INSERT INTO quotes (text, author) VALUES ('Štěstí je to jediné, co můžeme dávat, aniž bychom to měli.', 'Mark Rutherford');
INSERT INTO quotes (text, author) VALUES ('Cestování zabíjí předsudky, uzavřenost a úzkoprsost.', 'Mark Twain');
INSERT INTO quotes (text, author) VALUES ('Dokud budou kakaové boby růst na stromech, je pro mě čokoláda ovoce.', NULL);
INSERT INTO quotes (text, author) VALUES ('Svoboda není darem, nýbrž výsledkem společné vůle.', 'Jean-Jacques Rousseau');
INSERT INTO quotes (text, author) VALUES ('Měl jsem smůlu na obě manželky. Ta první mě opustila a ta druhá mě opustit nechtěla.', 'Patrick Murray');
INSERT INTO quotes (text, author) VALUES ('Jestliže skrz naskrz pochopíte žábu, dosáhnete osvícení.', 'Šunriju Suzuki');
INSERT INTO quotes (text, author) VALUES ('Sebevědomí je nejatraktivnější kvalita, kterou člověk může mít. Jak mohou ostatní vidět, jak jste úžasní, pokud to nevidíte Vy sami?', NULL);
INSERT INTO quotes (text, author) VALUES ('Život je krátký, žijte ho. Láska je vzácná, chyťte ji. Hněv je špatný, zbavte se ho. Strach je hrozný, čelte mu. Vzpomínky jsou sladké, važte si jich.', NULL);
INSERT INTO quotes (text, author) VALUES ('Zamilovaní zavírají při líbání oči, protože chtějí vidět srdcem.', 'Daphne Du Maurier');
INSERT INTO quotes (text, author) VALUES ('Víte co je to tragédie? Když se dívka vdá z lásky a po svatbě zjistí, že muž nemá žádné peníze.', 'Mark Twain');
INSERT INTO quotes (text, author) VALUES ('Lepší je vidět něco jednou, než o tom tisíckrát slyšet.', NULL);
INSERT INTO quotes (text, author) VALUES ('Uschlé listí nehyzdí krásné stromy.', 'Kurdské přísloví');
INSERT INTO quotes (text, author) VALUES ('Náš největší úspěch není v tom, že nepadneme, ale v tom, že vždy vstaneme, kdykoli padneme.', 'Konfucius');
INSERT INTO quotes (text, author) VALUES ('Nedovol názorům ostatních, aby se staly tvými.', NULL);
INSERT INTO quotes (text, author) VALUES ('Važte si sami sebe, protože jste jediní, kdo může něco pro svět udělat. Když si nebudete vážit sami sebe, Vaše pomoc nebude nic víc než iluze.', NULL);
INSERT INTO quotes (text, author) VALUES ('Nakonec se z nás všech stanou příběhy.', 'Margaret Atwood');
INSERT INTO quotes (text, author) VALUES ('Prvním a nejdůležitějším vzděláním je výchova příkladem.', 'Jean-Jacques Rousseau');
INSERT INTO quotes (text, author) VALUES ('Kdyby nikdo nikdy neriskoval, pak i Michelangelo vymaloval v Sixtinské kapli jen podlahu.', 'Neil Simon');
INSERT INTO quotes (text, author) VALUES ('Vše, co opravdu potřebuji znát, jsem se naučil v mateřské škole.', 'Robert Fulghum');
INSERT INTO quotes (text, author) VALUES ('Žvanění se často kryje s vágním myšlením.', 'Thomas Sowell');
INSERT INTO quotes (text, author) VALUES ('Důvodem, proč se neodvažujeme, není to, že jsou věcí obtížné; věci jsou obtížné proto, že se neodvažujeme.', 'Seneca');
INSERT INTO quotes (text, author) VALUES ('Není důležité, jak umění svět eticky soudí, nýbrž zda a jak pojmenovává, odhaluje a dává spatřit věci skrývané a skryté.', 'Sylvie Richterová');
INSERT INTO quotes (text, author) VALUES ('Vždy si pamatujte, že někde ve světě je někdo, kdo je spokojenější s větším málem, než máte Vy.', NULL);
INSERT INTO quotes (text, author) VALUES ('Musíte pochopit, mí drazí, že nejkratší vzdálenost mezi pravdou a lidským bytím je příběh.', 'Anthony de Mello');
INSERT INTO quotes (text, author) VALUES ('Každý člověk má jenom tolik minut, hodin a dní kolik jich využije.', 'Zig Ziglar');
INSERT INTO quotes (text, author) VALUES ('Ať už si myslíš, že to dokážeš, nebo že to nezvládneš, pokaždé máš pravdu.', 'Henry Ford');
INSERT INTO quotes (text, author) VALUES ('Nic velkého nebylo nikdy dosaženo bez nadšení.', 'Ralph Waldo Emerson');
INSERT INTO quotes (text, author) VALUES ('Snažím se pracovat každý den, i když nemám motivaci. Rituál je pro mě velmi důležitý.', 'Mel Ramos');
INSERT INTO quotes (text, author) VALUES ('Snaž se být duhou v mračnu někoho jiného.', 'Maya Angelou');
INSERT INTO quotes (text, author) VALUES ('Muži o lásce možná nemluví tolik jako ženy. Přesto když milují, milují doopravdy a se vším všudy.', NULL);
INSERT INTO quotes (text, author) VALUES ('Cítit, milovat, trpět, obětovat se, bude vždycky obsahem života ženy.', 'Honoré De Balzac');
INSERT INTO quotes (text, author) VALUES ('Abyste mohli dělat věci jinak, musíte je jinak i vidět.', 'Paul Allaire');
INSERT INTO quotes (text, author) VALUES ('Ať se dostanete kamkoliv, stane se toto místo vaší součástí.', 'Anita Desai');
INSERT INTO quotes (text, author) VALUES ('Vybuduj hřiště a zájemci se objeví.', 'Field of dreams');
INSERT INTO quotes (text, author) VALUES ('Láska je jako šachy. Dáma se vždycky zamiluje do koně.', NULL);
INSERT INTO quotes (text, author) VALUES ('Rozhodl jsem se, že všechny svoje úspory dám do alkoholu. Kde jinde mi dají 40%.', NULL);
INSERT INTO quotes (text, author) VALUES ('Každému připadají hvězdy jiné. Tomu, kdo cestuje, ukazují cestu. Pro jiného jsou to jen světélka na nebi. Pro vědce je to problém k řešení.', 'Antoine de Saint-Exupéry');
INSERT INTO quotes (text, author) VALUES ('Nebojte se postavit se za to, čemu věříte, i kdybyste za tím měli stát sami.', NULL);
INSERT INTO quotes (text, author) VALUES ('Existuje riziko, které si můžeme dovolit podstoupit a riziko, které si nemůžeme dovolit nepodstoupit.', 'Peter Drucker');
INSERT INTO quotes (text, author) VALUES ('Věřím, že nůžky v mých rukou dokáží více, než tužka.', 'Truman Capote');
INSERT INTO quotes (text, author) VALUES ('Pokud se podíváte opravdu pozorně, tak na většině úspěchů, jenž přišly ze dne na den, se pracovalo již dlouhou dobu předtím.', 'Steve Jobs');
INSERT INTO quotes (text, author) VALUES ('Den má 86400 vteřin. Tedy 86400 okamžiků.', NULL);
INSERT INTO quotes (text, author) VALUES ('Hrajeme hazardní hry, protože se nám život zdá být příliš předvídatelný a bezpečný.', 'Dan Savage');
INSERT INTO quotes (text, author) VALUES ('Pytle peněz nemusí být vždy jen symbolem ohromného bohatství, ale také ohromné inflace.', NULL);
INSERT INTO quotes (text, author) VALUES ('Láska to je štěstí, které si dáváme navzájem.', NULL);
INSERT INTO quotes (text, author) VALUES ('Strom na rozdíl od člověka vždy pozná svou porážku.', 'Ivan Fontana');
INSERT INTO quotes (text, author) VALUES ('Tak dlouho se chodí se džbánem pro pivo, až dojdou peníze!', NULL);
INSERT INTO quotes (text, author) VALUES ('Komár by byl oblíbený, kdyby místo krve sál tuk.', NULL);
INSERT INTO quotes (text, author) VALUES ('Není pravda, že máme málo času, pravdou ale je, že ho hodně promarníme.', 'Seneca');
INSERT INTO quotes (text, author) VALUES ('Děti, které se ptají PROČ, jsou ty, které změní svět.', 'Neal Thompson');
INSERT INTO quotes (text, author) VALUES ('Skoč, křídla roztáhneš cestou.', 'Ray Bradbury');
INSERT INTO quotes (text, author) VALUES ('Jsou dny, které by měl člověk radši prospat. Jako například dny od pondělí do pátku.', NULL);
INSERT INTO quotes (text, author) VALUES ('Skončil víkend: Kam se proboha poděla ta noc z pátku na neděli?!', NULL);
INSERT INTO quotes (text, author) VALUES ('Těžké časy vám dodávají odvahu k tomu, abyste mysleli na nemyslitelné.', 'Andy Grove');
INSERT INTO quotes (text, author) VALUES ('Můžu mít všechno, co chci, ale nemusím to mít dvakrát, nemusím to mít dvakrát větší a nemusím to mít dvakrát dražší, než je nutné.', 'Warren Buffett - tehdy nejbohatší muž světa');
INSERT INTO quotes (text, author) VALUES ('Jsme tím, co si myslíme. Ze svých myšlenek stavíme svůj svět.', 'Buddha');
INSERT INTO quotes (text, author) VALUES ('Stárnutí je otrava, ale je to jediný způsob, jak se dožít vysokého věku.', 'G. B. Shaw');
INSERT INTO quotes (text, author) VALUES ('Zpětná vazba neobsahuje absolutní pravdu, ale je pravdivá v očích toho, kdo ji poskytuje.', NULL);
INSERT INTO quotes (text, author) VALUES ('Věta by neměla obsahovat žádná zbytečná slova a odstavce by neměly obsahovat zbytečné věty ze stejného důvodu,', NULL);
INSERT INTO quotes (text, author) VALUES ('Žádné dítě není tak roztomilé, aby matka nebyla šťastná, když konečně usne.', 'Ralph Waldo Emerson');
INSERT INTO quotes (text, author) VALUES ('Je třeba být si trochu podobni, abychom si rozuměli, ale trochu rozdílní, abychom se milovali.', 'Jean-Jacques Rousseau');
INSERT INTO quotes (text, author) VALUES ('Kreativita může vyřešit téměř jakýkoliv problém. Tvůrčí akt, porážka zvyku originalitou, překoná všechno.', 'George Lois');
INSERT INTO quotes (text, author) VALUES ('V přírodě nenajdeš dva stejné stromy, dva stejné klasy…', NULL);
INSERT INTO quotes (text, author) VALUES ('Dobré věci přicházejí k těm, kteří čekají. Velké věci přicházejí k těm, kteří zvednou zadek a dělají něco pro to, aby přišly.', NULL);
INSERT INTO quotes (text, author) VALUES ('Duchovní život je život za hranicemi běžných nálad. Je to život, v němž si volíme radost a nedovolujeme sami sobě stát se oběťmi pocitů štěstí nebo sklíčenosti.', 'Henri J. M. Nouwen');
INSERT INTO quotes (text, author) VALUES ('Co slyším, to zapomenu. Co vidím, to si pamatuji. Co si vyzkouším, tomu taky rozumím.', 'Confucius');
INSERT INTO quotes (text, author) VALUES ('Nepoužívejte příliš velká slova pro vaše téma. Nepište nekonečně, když chcete říct velmi, jinak nebudete mít slovo, když budete chtít mluvit o něčem opravdu nekonečném. C. S. Lewis', NULL);
INSERT INTO quotes (text, author) VALUES ('Každé dítě je umělec. Problém je, jak má zůstat umělcem, až jednou vyroste.', 'Pablo Picasso');
INSERT INTO quotes (text, author) VALUES ('Zřídkakdy je vhodné říci všechno.', 'Strunk and White');
INSERT INTO quotes (text, author) VALUES ('Když píšu o zloději koní, chcete, abych napsal, že krást koně je špatné. Ale to přece každý ví!', 'A. P. Čechov');
INSERT INTO quotes (text, author) VALUES ('Nejdřív máme děti na rukou, potom na klíně a nakonec na krku.', 'japonské přísloví');
INSERT INTO quotes (text, author) VALUES ('Teprve až pokácíte poslední strom,\r\naž otrávíte poslední řeku,\r\naž ulovíte poslední rybu,\r\nteprve tehdy přijdete na to,\r\nže peníze se nedají jíst.\r\n', 'Indiáni kmene Cee');
INSERT INTO quotes (text, author) VALUES ('Problémy jsou nevyhnutelnou součástí života. Očekávej je a až přijdou, drž hlavu zpříma, podívej se jim přímo do očí a řekni: Jsem větší než vy, neporazíte mě.', 'Ann Landersová');
INSERT INTO quotes (text, author) VALUES ('Je těžké zbavit se vad, jež s námi vyrostly.', 'Seneca mladší');
INSERT INTO quotes (text, author) VALUES ('Stromy, jichž se mohu bezprostředně dotýkat a z nichž cítím ohromnou energii - růstové fluidum.\r\nVždyť každoročně - po celý svůj život - mi demonstrují své znovuzrození.', 'J. W. Goethe');
INSERT INTO quotes (text, author) VALUES ('Když jsem s tebou, hodiny utíkají jako vteřiny. Když jsem bez tebe, dny mi připadají jako roky.', NULL);
INSERT INTO quotes (text, author) VALUES ('Svět nezajímá, co všechno víte a znáte. Svět se zajímá jen o to, co děláte s tím, co víte a znáte.', 'Tony Wagner');
INSERT INTO quotes (text, author) VALUES ('Polibek je krásný vynález přírody, jak zastavit řeč, když už jsou slova zbytečná.', 'Ingrid Bergmanová');
INSERT INTO quotes (text, author) VALUES ('Čas musíme využívat kreativně a s vědomím, že doba je vždy zralá na konání dobra.', 'Martin Luther King jr.');
INSERT INTO quotes (text, author) VALUES ('Pouze ti, kteří se odváží jít příliš daleko, mohou přijít na to, jak daleko se dá jít.', 'T. S. Eliot');
INSERT INTO quotes (text, author) VALUES ('Jsem vděčný všem, kteří mi řekli NE. Díky nim jsem to totiž zvládl sám.', 'Albert Einstein');
INSERT INTO quotes (text, author) VALUES ('Archeolog je ten nejlepší manžel, jakého si žena může přát; čím je žena starší, tím je pro něj zajímavější.', 'Agatha Christie');
INSERT INTO quotes (text, author) VALUES ('Svědomí je nejlepší kompas, který máme.', 'Jean-Jacques Rousseau');
INSERT INTO quotes (text, author) VALUES ('Motivace je to, díky čemuž začnete. Zvyk je to, díky čemuž v tom budete pokračovat.', 'Jim Ryan');
INSERT INTO quotes (text, author) VALUES ('Cestovat znamená nacházet věci, které by tě nikdy nenapadlo hledat.', NULL);
INSERT INTO quotes (text, author) VALUES ('Dům bez dětí je jako zvon bez srdce.', 'Sylva');
INSERT INTO quotes (text, author) VALUES ('Nepiju alkohol. Pouze dezinfikuji svoji duši.', NULL);
INSERT INTO quotes (text, author) VALUES ('Úspěch je chůze od neúspěchu k neúspěchu bez ztráty nadšení.', 'Winston Churchill');
INSERT INTO quotes (text, author) VALUES ('Je pravda, že tvrdá práce ještě nikdy nikoho nezabila, ale já si říkám, proč to riskovat?', 'Ronald Reagan');
INSERT INTO quotes (text, author) VALUES ('Zásadovost je posledním útočištěm lidí bez představivosti.', 'Oscar Wilde');
INSERT INTO quotes (text, author) VALUES ('Tvůrčí práce je hra. Je to svobodná úvaha s použitím materiálů ve tvaru, který si člověk zvolí.', 'Stephen Nachmanovitch');
INSERT INTO quotes (text, author) VALUES ('Odchýlit se od norem znamená, že na to musíte mít. Než začnete být tvořiví, musíte být odvážní. Tvořivost je osud, ale odvaha je cestou.', 'Joye Reiman');
INSERT INTO quotes (text, author) VALUES ('Vykonávat věc, které se bojíme, je první krok k úspěchu.', 'Mahátma Gándhí');
INSERT INTO quotes (text, author) VALUES ('Romantické citáty a myšlenky slavných i neznámých autorů zamilované muže potěší stejně jako zamilované ženy.', NULL);
INSERT INTO quotes (text, author) VALUES ('Musíte být schopni dělat dnes věci, které ostatní nedělají, abyste zítra měli věci, které ostatní nikdy mít nebudou.', 'Les Brown');
INSERT INTO quotes (text, author) VALUES ('Pokud opravdu chcete dosáhnout úspěchu, nikdy se nevzdávejte. A to bez ohledu na to, do jak špatné situace se můžete dostat.', NULL);
INSERT INTO quotes (text, author) VALUES ('Neexistence pointy v dramatu neosvobuzuje diváky od povinnosti opustit sál.', 'S. J. Lec');
INSERT INTO quotes (text, author) VALUES ('I na malé cestě se dají zažít velká dobrodružství.', NULL);
INSERT INTO quotes (text, author) VALUES ('Příběhy, kde se lidé učí z chyb druhých, jsou známkou civilizované společnosti.', 'Terry Pratchett');
INSERT INTO quotes (text, author) VALUES ('Nikdy nepoužívejte dlouhé slovo, které může být nahrazeno krátkým.', 'George Orwell');
INSERT INTO quotes (text, author) VALUES ('Pokud mi něco vysvětlujete, je to esej. Pokud mi něco přímo ukazujete, je to příběh.', 'Barbara Greene');
INSERT INTO quotes (text, author) VALUES ('Dělat z jednoduchého složité je zcela běžné. Ale vytvářet z komplikovaných věcí díla jednoduchá, to je opravdová kreativita!', 'Charles Mingus');
INSERT INTO quotes (text, author) VALUES ('Vše, co si dokážete představit, je skutečné.', 'Pablo Picasso');
INSERT INTO quotes (text, author) VALUES ('Ženy mají dvě zbraně - kosmetiku a slzy. Naštěstí pro muže mohou být jen zřídkakdy s úspěchem použity obě současně.', 'Napoleon Bonaparte');
INSERT INTO quotes (text, author) VALUES ('Opravdová láska je umění najít ve světě někoho, s kým si rozumíš lépe, než se sebou samým.', 'Henri Fréderic Amiel');
INSERT INTO quotes (text, author) VALUES ('Máme se od každého, kdo se ocitne v našem životě, něco naučit. Některé lekce jsou bolestivé, jiné bezbolestné, ale všechny jsou k nezaplacení.', NULL);
INSERT INTO quotes (text, author) VALUES ('Správně stanovený cíl je polovina úspěchu.', 'Zig Ziglar');
INSERT INTO quotes (text, author) VALUES ('Kdo sází stromy, má druhé raději, než sebe.', 'Staré anglické rčení');
INSERT INTO quotes (text, author) VALUES ('Život je jako fotografie. Také potřebujete negativy k rozvoji.', NULL);
INSERT INTO quotes (text, author) VALUES ('Dítě není žádný stroj, proto nelze vyslovit radu nebo návod k upotřebení či použití. Každá situace je jiná, každé dítě je jiné.', NULL);
INSERT INTO quotes (text, author) VALUES ('Průměrný učitel vypráví. Dobrý učitel vysvětluje. Výborný učitel ukazuje. Nejlepší učitel inspiruje.', 'Charles Farrar Browne');
INSERT INTO quotes (text, author) VALUES ('Mnohem těžší než dostat ženu do postele, je dostat jí ráno z postele.', 'Talmer');
INSERT INTO quotes (text, author) VALUES ('Až jednoho dne ucítíš velké prázdno, jez. Je to hlad!', NULL);
INSERT INTO quotes (text, author) VALUES ('Pracujte tak, jako byste na všechno měli jen jeden den času.', 'Zig Ziglar');
INSERT INTO quotes (text, author) VALUES ('Sebedůvěra je schopnost vidět sebe sama jako schopného a způsobilého člověka, který dokáže lásku přijímat i dávat, který je jedinečný a kterého lidé uznávají.', 'Patricia H. Berneová, Louis M. Savary');
INSERT INTO quotes (text, author) VALUES ('Největší chyba, kterou v životě můžete udělat, je mít pořád strach, že nějakou uděláte.', 'Elbert Hubbard');
INSERT INTO quotes (text, author) VALUES ('Cesta k úspěchu a cesta k neúspěchu jsou téměř přesně stejné.', 'Colin R. Davis');
INSERT INTO quotes (text, author) VALUES ('Krása je moc, kterou žena okouzluje milence, a děsí manžela.', 'Ambrose Bierce');
INSERT INTO quotes (text, author) VALUES ('Stavu větví nejlépe prospívá péče o kořeny.', NULL);
INSERT INTO quotes (text, author) VALUES ('Vrátit se tam, odkud pocházíte, není to samé, jako nikdy neodejít.', 'Terry Pratchett');
INSERT INTO quotes (text, author) VALUES ('Není toho moc, co by mělo být řečeno o souvětí s výjimkou toho, že většina spisovatelů neví, kdy má souvětí ukončit.', 'William Zinsser');
INSERT INTO quotes (text, author) VALUES ('Každé ráno máme po zazvonění budíku úplně novou příležitost udělat v čase, který nám byl darován, to, co chceme. A po celý zbytek života budeme tento dar dostávat znovu a znovu.', 'Hyrum Smith');
INSERT INTO quotes (text, author) VALUES ('Rodiče, na které děti zapomněly, jsou jako stromy bez listí.', 'Korejské přísloví');
INSERT INTO quotes (text, author) VALUES ('Cestování je jediná věc, kterou si koupíš a učiní tě bohatším.', NULL);
INSERT INTO quotes (text, author) VALUES ('Na dně hlavního proudu řeky nacházíme pouze průměrnost.', 'Jonas Ridderstrale');
INSERT INTO quotes (text, author) VALUES ('Daň z cigaret má lidi odradit od kouření, daň z alkoholu od pití a daň ze mzdy…', NULL);
INSERT INTO quotes (text, author) VALUES ('Nulová rozmanitost zabíjí tvořivost. Stejnost plodí stejné a ještě více stejného.', 'Jonas Ridderstrale');
INSERT INTO quotes (text, author) VALUES ('Sněte si svůj vlastní sen. Nebo si Vás najme někdo jiný, abyste snili ten jeho.', 'Farrah Gray');
INSERT INTO quotes (text, author) VALUES ('Máš ujít deset mil a už jsi ušel devět? Raduj se, jsi v polovině cesty!', 'zenové úsloví');
INSERT INTO quotes (text, author) VALUES ('Síla příběhu. Neodcházejte bez ní z domu. A nikdy, nikdy, nikdy ji nepodceňujte!', 'Terry Pratchett');
INSERT INTO quotes (text, author) VALUES ('Cestování zlepšuje naši představivost, uspokojuje naši zvědavost a připomíná nám, kolik máme všichni společného.', 'Deborah Lloyd');
INSERT INTO quotes (text, author) VALUES ('Vše, co potřebuji k životu, je spát pod hvězdnou oblohou, probudit se do švitoření ptáků a vychutnat si kávu při ranním svitu slunce.', NULL);
INSERT INTO quotes (text, author) VALUES ('Pokud jsme v něčem úspěšní, není to práce, je to životní styl.', 'Granatelli');
INSERT INTO quotes (text, author) VALUES ('Rostoucí strom je živým symbolem pokrokového národa.', 'D. Nehrů');
INSERT INTO quotes (text, author) VALUES ('Postavení umělce je pokorné. Je ve své podstatě kanálem.', 'Piet Mondrian');
INSERT INTO quotes (text, author) VALUES ('Jednou ranou strom nepadá.', NULL);
INSERT INTO quotes (text, author) VALUES ('Neučme děti to, co si mohou samy objevit.', 'Jean-Jacques Rousseau');
INSERT INTO quotes (text, author) VALUES ('Nic není dobré ani špatné, pouze naše myšlení to činí takovým či onakým.', 'William Shakespeare');
INSERT INTO quotes (text, author) VALUES ('Zapomeňte na všechno, co jste slyšeli o prvním dojmu. Mnohem důležitější je poslední dojem. Ten si totiž budou všichni pamatovat.', 'Liz Danzico');
INSERT INTO quotes (text, author) VALUES ('Mezi nejdůležitější věty v každém textu patří ta první. Pokud nepřiměje čtenáře, aby přistoupil k druhé větě, váš text je mrtvý. A pokud ho druhá věta nezaujme tak, aby pokračoval ke třetí větě, je stejně mrtvý. Takové vrstvení, které nutí čtenáře neustále pokračovat, dokud ho příběh nepohltí, je pro spisovatele životně důležitá dovednost.', 'William Zinsser');
INSERT INTO quotes (text, author) VALUES ('Láska je bezproblémová jako vozidlo. Problematičtí jsou pouze řidiči, cestující a cesta.', 'Franz Kafka');
INSERT INTO quotes (text, author) VALUES ('Hodina výtvarné výchovy pro mě byla jako náboženský obřad. Dříve než jsem se dotkl papíru nebo tužky, pečlivě jsem si umyl ruce. Pracovní nástroje pro mě byly posvátnými předměty.', 'Joan Miró');
INSERT INTO quotes (text, author) VALUES ('Nejlepší pomsta je obrovský úspěch.', 'Frank Sinatra');
INSERT INTO quotes (text, author) VALUES ('Naše současné výsledky nejsou nic jiného než výsledek našeho dřívějšího uvažování. Jsme tam, kam nás naše myšlenky přivedly, a zítra budeme tam, kam nás dovedou naše dnešní úvahy.', 'Blaise Pascal');
INSERT INTO quotes (text, author) VALUES ('Cesta dlouhá i 1000 mil vždy začíná prvním krokem.', 'Lao Tzu');
INSERT INTO quotes (text, author) VALUES ('Naše běžná realita je hustě zaplněná absurdními zprávami a znameními. Všimněte si jich. Mají nejen sociální význam, ale často jsou dost nepředvídatelným úvodem k odlišení jednoho jedince od druhého.', 'William Zinsser');
INSERT INTO quotes (text, author) VALUES ('Jestli najdeš v životě cestu bez překážek, pravděpodobně nikam nevede.', 'Arthur C. Clarke');
INSERT INTO quotes (text, author) VALUES ('Skutečná svoboda člověka nespočívá v tom, aby dělal co che, nýbrž spíš v tom, aby nikdy nedělal, co nechce.\r\n', 'Jean-Jacques Rousseau');
INSERT INTO quotes (text, author) VALUES ('Spousta tvorů je inteligentních, ale jen jediný vypráví příběhy - a to jsme my.', 'Terry Pratchett');
INSERT INTO quotes (text, author) VALUES ('Nešťastná láska není to nejhorší. To pravé neštěstí je nemilovat.', 'Eduard Bass');
INSERT INTO quotes (text, author) VALUES ('Nejděsivější je to vždycky před začátkem psaní. Pak už vše může být jenom lepší.', 'Stephen King');
INSERT INTO quotes (text, author) VALUES ('Pokud opravdu chcete něco udělat, tak najdete cestu. Pokud tak neučiníte, tak najdete výmluvu.', 'Jim Rohn');
INSERT INTO quotes (text, author) VALUES ('Vypravování odhaluje smysl všeho, aniž by se dopustilo špatné definice.', 'Hannah Arendt');
INSERT INTO quotes (text, author) VALUES ('Kdo dal život dítěti, stává se jeho dlužníkem.', 'Fabroe');
INSERT INTO quotes (text, author) VALUES ('V životě jsou tři věci, které už nevrátíte. Slovo, které jste vyřknuli, moment, který jste propásli a čas, který uplynul. Buďte proto opatrní.', NULL);
INSERT INTO quotes (text, author) VALUES ('Každá kniha by měla být zábavná. A dobrá kniha bude více, v žádném případě ne méně.', 'C. S. Lewis');
INSERT INTO quotes (text, author) VALUES ('Když celý svět křičí: Vzdej to!, naděje šeptá: Zkus to ještě jednou.', NULL);
INSERT INTO quotes (text, author) VALUES ('Je těžké čekat na něco, co víte, že se možná nikdy nestane. Ale je ještě těžší vzdát se, když víte, že to je to jediné, co opravdu chcete.', NULL);
INSERT INTO quotes (text, author) VALUES ('Člověk, který cestuje s touhou dozvědět se, směřuje přes všechny dálky hlavně k sobě samému.', 'Jan Werich');
