#!/bin/bash

# utf8-test.sh
# Test UTF-8 a Unicode podpory v terminálu

echo "=========================================="
echo "           UTF-8 TERMINAL TEST"
echo "=========================================="
echo ""

echo "1. ČESKÉ ZNAKY - MALÁ PÍSMENA:"
echo "příliš žluťoučký kůň úpěl ďábelské ódy!"
echo ""

echo "2. ČESKÉ ZNAKY - VELKÁ PÍSMENA:"
echo "PŘÍLIŠ ŽLUŤOUČKÝ KŮŇ ÚPĚL ĎÁBELSKÉ ÓDY!"
echo ""

echo "3. ZÁKLADNÍ SYMBOLY:"
echo "1. ✓ (checkmark)"
echo "2. ✗ (cross mark)"
echo "3. ⚠ (warning)"
echo "4. ★ (star)"
echo "5. ♥ (heart)"
echo "6. → (arrow right)"
echo "7. ← (arrow left)"
echo "8. © (copyright)"
echo "9. ® (registered)"
echo "10. € (euro)"
echo ""

echo "4. EMOJI - ZÁKLADNÍ:"
echo "11. 😀 (grinning face)"
echo "12. 😊 (smiling face)"
echo "13. 😍 (heart eyes)"
echo "14. 🤔 (thinking)"
echo "15. 👍 (thumbs up)"
echo "16. 🔥 (fire)"
echo "17. 💯 (hundred)"
echo "18. 🎉 (party)"
echo "19. ❤️ (red heart)"
echo "20. 🚀 (rocket)"
echo ""

echo "5. TECHNICKÉ SYMBOLY:"
echo "21. ⚙️ (gear)"
echo "22. 🔧 (wrench)"
echo "23. 🐛 (bug)"
echo "24. 📁 (folder)"
echo "25. 📄 (document)"
echo "26. 💻 (laptop)"
echo "27. 🌐 (globe)"
echo "28. 🔒 (lock)"
echo "29. 🔑 (key)"
echo "30. ⏰ (clock)"
echo ""

echo "6. POKROČILÉ UNICODE:"
echo "31. ∞ (infinity)"
echo "32. π (pi)"
echo "33. α (alpha)"
echo "34. β (beta)"
echo "35. ≠ (not equal)"
echo "36. ≤ (less than or equal)"
echo "37. ≥ (greater than or equal)"
echo "38. ± (plus minus)"
echo "39. × (multiplication)"
echo "40. ÷ (division)"
echo ""

echo "=========================================="
echo "Zadej čísla symbolů které NEVIDÍŠ správně:"
echo "Například: 11,15,22 (odděl čárkou)"
echo "Nebo 'OK' pokud vše funguje správně"
echo "=========================================="